# Generated by Django 5.2.7 on 2025-11-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Заголовок")),
                ("content", models.TextField(verbose_name="Содержимое")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_published",
                    models.BooleanField(verbose_name="Опубликовано или нет"),
                ),
                ("views_count", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "запись в блоге",
                "verbose_name_plural": "записи в блоге",
                "ordering": ["title"],
            },
        ),
    ]
